name: rode-dev-env
author: rode@liatrio.com
description: A test environment for Rode and its components
branding:
  icon: anchor
  color: green

inputs:
  rodeVersion:
    description: "Rode version. Set this value to 'local' to skip initializing Rode."
    required: true
    default: "0.14"
  elasticsearchVersion:
    description: 'Elasticsearch Docker image tag.'
    required: true
    default: "7.10.0"
  grafeasVersion:
    description: 'Grafeas Elasticsearch Docker image tag.'
    required: true
    default: "0.8"
  opaVersion:
    description: 'Open Policy Agent Docker image tag.'
    required: true
    default: "0.24.0"
  stage:
    description: "One of either main or post"
    required: true
    default: "main"

outputs:
  rodeHost:
    description: 'Rode hostname and port. No protocol.'
    value: ${{ steps.outputs.rode-dev-env.rodeHost }}
  elasticsearchUrl:
    description: 'Elasticsearch URL.'
    value: ${{ steps.outputs.rode-dev-env.elasticsearchUrl }}
  grafeasElasticsearchHost:
    description: 'Grafeas Elasticsearch host and port. No protocol.'
    value: ${{ steps.outputs.rode-dev-env.grafeasElasticsearchHost }}
  opaUrl:
    description: 'Open Policy Agent URL.'
    value: ${{ steps.outputs.rode-dev-env.opaUrl }}

runs:
  using: composite
  steps:
    - run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        INPUT_RODEVERSION: ${{ inputs.rodeVersion }}
        INPUT_ELASTICSEARCHVERSION: ${{ inputs.elasticsearchVersion }}
        INPUT_GRAFEASVERSION: ${{ inputs.grafeasVersion }}
        INPUT_OPAVERSION: ${{ inputs.opaVersion }}
        INPUT_STAGE: ${{ inputs.stage }}
