name: rode-dev-env
author: rode@liatrio.com
description: A test environment for Rode and its components
branding:
  icon: anchor
  color: green

inputs:
  authEnabled:
    description: "Whether Rode should be configured with authentication."
    required: true
    default: "false"
  rodeVersion:
    description: "Rode version. Set this value to 'local' to skip initializing Rode."
    required: true
    default: "0.14"
  elasticsearchVersion:
    description: "Elasticsearch Docker image tag."
    required: true
    default: "7.10.0"
  grafeasVersion:
    description: 'Grafeas Elasticsearch Docker image tag.'
    required: true
    default: "0.8"
  opaVersion:
    description: 'Open Policy Agent Docker image tag.'
    required: true
    default: "0.24.0"

outputs:
  rodeHost:
    description: "Rode hostname and port. No protocol."
  elasticsearchUrl:
    description: "Elasticsearch URL."
  grafeasElasticsearchHost:
    description: "Grafeas Elasticsearch host and port. No protocol."
  opaUrl:
    description: "Open Policy Agent URL."
  oidcProviderUrl:
    description: "OpenID Connect provider URL."

runs:
  using: node12
  main: dist/index.js
  post: dist/index.js
