#!/bin/bash

set -euo pipefail

export INPUT_RODEVERSION='0.14'
export INPUT_ELASTICSEARCHVERSION='7.10.0'
export INPUT_GRAFEASVERSION='0.8'
export INPUT_OPAVERSION='0.24.0'
export INPUT_AUTHENABLED='false'
