name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node Setup
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.13.1 # GitHub Actions Runtime Node version
      - name: Install Dependencies
        run: yarn install --production
      - name: Build
        run: |
          yarn clean
          yarn build
      - name: Commit Bundle & Tag Release
        run: |
          set -eu
          git config --local user.email "rode@liatrio.com"
          git config --local user.name "rode-bot"

          git add dist/index.js
          git commit -m "Update action dist"

          version="v$(jq -r '.version' < package.json)"
          git tag -a "${version}" -m "Release ${version}"
          git push --follow-tags
