name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: 12.13.1 # GitHub Actions Runtime Node version
      - name: Install Dependencies
        run: yarn install --production
      - name: Build
        id: build
        run: |
          ./build.sh
      - name: Commit Bundle & Tag Release
        run: |
          set -eu
          git config --local user.email "rode@liatrio.com"
          git config --local user.name "rode-bot"

          commitMsg="Release ${{ steps.build.outputs.version }}"
          git add dist/index.js
          git commit -m "$commitMsg"

          git tag -a "${{ steps.build.outputs.version }}" -m "$commitMsg"
          git push --follow-tags
