name: test

on: push

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Local rode-dev-env
        id: rode
        uses: ./
      - name: Check Rode Running
        run: |
          set -euo pipefail

          curl --fail -d '{"name": "test"}' http://${{ steps.rode.outputs.rodeHost }}/v1alpha1/policy-groups
          curl --fail http://${{ steps.rode.outputs.rodeHost }}/v1alpha1/policy-groups | jq
